DeepSourceCorp/globstar

- Cargo.lock
- globstar/Cargo.toml
- globstar/src/context.rs
- globstar/src/lib.rs
- adds documentation to all public items (`cargo doc --open`)
- adds doc tests to all relevant APIs in the `globstar` crate (`cargo test`)
fixes LAE-5572
> add doc tests to the globstar crate

- globstar/src/context.rs
- globstar/src/lib.rs
previously, scopes were mandatory to construct a Context. this meant that it was impossible to construct a Context that only comprises of injections and no scopes.
with these changes Context may be constructed with empty scopes and empty injections too.
> make scopes in Context optional

- Cargo.lock
- globstar/Cargo.toml
- globstar/examples/injections/injections.scm
- globstar/examples/injections/main.rs
- globstar/examples/readme.md
- globstar/examples/scopes/main.rs
- globstar/examples/scopes/scopes.scm
- globstar/examples/simple/main.rs
fixes LAE-5480, copying `/globstar/examples/readme.md`:
---
The `examples` directory contains the following example
analyzers, in increasing order of complexity:
- `simple`: a basic `globstar` analyzer targeting Rust
- `scopes`: an example that covers scope-resolution and
scoping queries
- `injections`: an example that covers language injections
using multiple tree-sitter grammars
To run the tests for any example:
```shell
$ cargo test --features testing --example simple
```
> add examples

- Makefile
- goreleaser.yaml
- pkg/cli/cli.go
- pkg/cli/version.go
This PR adds proper version information to the Globstar CLI. The changes include:
- Adding a version variable in the `pkg/cli` package that gets populated during build time
- Updating build flags in both `Makefile` and `goreleaser.yaml` to inject the version information
- Adding additional CLI info (name, usage, description)
- Using `git describe --tags` for local builds to show the current version/tag
The version can now be displayed using the `--version` flag in the CLI.
Related: #35
> feat: add version flag in the CLI

- checkers/php/dangerous_eval.test.php
- checkers/php/dangerous_eval.yml
This PR introduces a new security checker named `dangerous_eval` to detect unsafe usage of `eval()` in PHP code. The use of `eval()` can lead to severe security vulnerabilities, including remote code execution (RCE), especially when combined with user-controlled input.
The checker flags the following unsafe patterns:
> php: dangerous eval

- checkers/docker/avoid_sudo.test.Dockerfile
- checkers/docker/avoid_sudo.yml
This PR introduces a new rule to detect and warn against the use of `sudo` in `RUN` commands within Dockerfiles. Since Docker containers execute commands as the root user by default, using `sudo` is unnecessary.
The recommend approach is to define a non-root User and prevent the use of `sudo`. This will help prevent privilege escalation attacks. The checker for this would require an reverse-pattern though, see #126.
A relevant article on best practices: [Dockerfile Security Best Practices](https://cloudberry.engineering/article/dockerfile-security-best-practices)  
```dockerfile
RUN sudo apt update && sudo apt install -y curl
RUN sudo rm -rf /
> docker: avoid using `sudo` in RUN commands

- checkers/docker/avoid_add.test.Dockerfile
- checkers/docker/avoid_add.yml
This PR adds a checker to detect the use of the `ADD` instruction in Dockerfiles; If used for copying files `ADD` has certain side effects, for example - The ability to do automatic archive extraction and remote URL downloads which can introduce security risks. This checker warns the user and tells them to prefer the `COPY` instruction instead.
See - [Dockerfile Best Practices](https://cloudberry.engineering/article/dockerfile-security-best-practices/)
```dockerfile
ADD https://example.com/file.tar.gz /destination/
```
> docker: avoid the use of the `ADD` instruction

- checkers/docker/avoid_latest.test.Dockerfile
- checkers/docker/avoid_latest.yml
This PR introduces a new rule to detect and warn against the use of the `latest` tag in Docker images. Since the `latest` tag can point to different versions of the image over time, it can lead to non-reproducible builds and unexpected changes. This rule encourages specifying a fixed version to ensure reliability.  
A stack overflow answer on the topic: [link](https://stackoverflow.com/questions/72889955/is-it-bad-practice-to-use-mysqllatest-as-docker-image)
```dockerfile
FROM python:latest
> docker: avoid the use of `latest` tag

- checkers/python/weak-ssl-version.test.py
- checkers/python/weak-ssl-version.yml
Test logs
```
echo "Testing built-in rules..."
Running test case: avoid_add.yml
Running test case: avoid_latest.yml
Running test case: avoid_sudo.yml
Running test case: weak-ssl-version.yml
All tests passed        globstar.dev/cmd/globstar               coverage: 0.0% of statements
globstar.dev/pkg/cli            coverage: 0.0% of statements
globstar.dev/pkg/config         coverage: 0.0% of statements
ok      globstar.dev/pkg/analysis       0.005s  coverage: 22.7% of statements
Total coverage: …
```
> chore: add checker to detect usage of weak SSL version

- checkers/python/hashid-with-django-secret.test.py
- checkers/python/hashid-with-django-secret.yml
Test logs:
```
Running test case: hashid-with-django-secret.yml
All tests passed%                  
```
> chore: add checker to detect usage of django secret key used as salt in HashID

- pkg/cli/cli.go
Add tracking of failed tests and use that to raise a non-zero exit code at the end. This way we can ensure that all the test cases run and the CI can break if anything is failing.
Fixes #155.
> fix: return non-zero exit code if checks fail

- checkers/rust/avoid_unwrap.test.rs
- checkers/rust/avoid_unwrap.yml
This PR adds a new rust checker to detect the use of `.unwrap()` in Rust code. While `.unwrap()` is convenient, it can lead to unexpected panics and is only meant for quick prototyping (see [rust error handling](https://doc.rust-lang.org/book/ch09-03-to-panic-or-not-to-panic.html#examples-prototype-code-and-tests)). This checker is flagged as an `antipattern` since it does not impact security much.
The checker flags the following cases:
Instead of using `.unwrap()`, consider:
- Handling errors explicitly using `match` or `if let`
- Using `.unwrap_or_else()` to provide a fallback value or handle errors gracefully
- Using `.expect()` with a meaningful message if a panic is intentional  
To reduce noise, the checker does not flag occurrences in test files, vendor dependencies, or test …
> rust: avoid using unwrap()

- checkers/ruby/ssl_no_verify.test.rb
- checkers/ruby/ssl_no_verify.yml
**Description**  
This PR adds a new Ruby checker to detect the use of `OpenSSL::SSL::VERIFY_NONE`, which disables SSL/TLS certificate verification. Disabling verification exposes applications to Man-in-the-Middle (MITM) attacks, allowing attackers to intercept and manipulate sensitive data in transit. This checker is flagged as a security issue to ensure SSL certificates are always validated.
**Detection Logic**  
- Setting `ssl_context.verify_mode = OpenSSL::SSL::VERIFY_NONE`
**Recommended Alternatives**  
Instead of disabling SSL verification, consider:  
- Using `OpenSSL::SSL::VERIFY_PEER` to verify certificates and ensure secure communications.  
- Properly configuring trusted certificate authorities (CAs) for SSL connections.
**Exclusions** …
> checker: ruby_ssl_no_verify

- checkers/ruby/skip_authorization.test.rb
- checkers/ruby/skip_authorization.yml
**Description**  
This PR adds a new Ruby checker to detect the use of `skip_authorization_check`, which skips essential authorization checks. Skipping these checks can expose applications to unauthorized access, allowing users to perform actions or access data beyond their permissions. This checker is flagged as a critical security issue to prevent privilege escalation and data leakage.
**Detection Logic**  
- Usage of methods matching `skip_authorization_check*`
**Recommended Alternatives**  
Instead of skipping authorization checks, consider:  
- Removing `skip_authorization_check` calls.  
- Implementing proper authorization mechanisms using libraries like:  
- [CanCanCan](https://github.com/CanCanCommunity/cancancan)  
- …
> checker: ruby_skip_authorization

- checkers/checker.go
- checkers/javascript/sql_injection.go
- checkers/javascript/testdata/sql_injection.test.js
This pull request introduces a Go-based static analysis checker designed to detect potential SQL injection vulnerabilities in JavaScript code. 
**Injection** is the **3rd most critical** web security risk in the [OWASP Top 10](https://owasp.org/Top10/A03_2021-Injection/). Among 94% of tested applications, it had a maximum incidence rate of 19% and an average of 3%. SQL injection remains a key pentesting target, making proper query sanitization essential to prevent unauthorized access and data loss.
The scanner works in two phases, during the first phase, it goes through and creates a map of all known variables in a file. This allows it to track where each variable is assigned a value, this is needed later on for detecting SQL injection vulnerabilities.
During the second phase, the scanner …
> feat(javascript): implement Go-based SQL injection checker

- checkers/ruby/sha1_weak_hash.test.rb
- checkers/ruby/sha1_weak_hash.yml
**Description**  
This PR adds a new Ruby checker to detect the use of `Digest::SHA1`, which relies on the SHA-1 hashing algorithm. SHA-1 is considered cryptographically weak and is vulnerable to collision attacks, exposing applications to data forgery and integrity breaches. This checker is flagged as a critical security issue to ensure stronger hashing mechanisms are used.
**Detection Logic**  
[x] Usage of `Digest::SHA1` for hashing sensitive data.
**Recommended Alternatives**  
Instead of using SHA-1, replace it with a stronger hashing algorithm such as `Digest::SHA256`:  
**Examples**  
ruby
**Insecure (vulnerable to collisions)**
Digest::SHA1.hexdigest("sensitive_data")
**Secure (recommended)**
Digest::SHA256.hexdigest("sensitive_data") …
> checker: ruby_sha1_weak_hash

- checkers/ruby/rsa_weak_crypto.test.rb
- checkers/ruby/rsa_weak_crypto.yml
This PR adds a new Ruby checker to detect the use of `OpenSSL::PKey::RSA` for cryptographic operations. RSA is considered outdated and insecure, especially with small key sizes (e.g., 1024-bit), making it vulnerable to brute-force and key leakage attacks. This checker is flagged as a critical security issue to encourage the use of modern and secure cryptographic alternatives.
- Usage of `OpenSSL::PKey::RSA` for encryption, decryption, or key generation.
- **Weak Key Sizes:** RSA with 1024-bit keys is susceptible to brute-force attacks.  
- **Poor Randomness:** Flaws in RSA signatures can expose private keys.  
- **Outdated Standard:** Modern cryptographic standards discourage RSA usage in favor of more secure algorithms.
Instead of RSA, consider: …
> checker: ruby_rsa_weak_crypto

- checkers/ruby/rails_unsafe_direct_assignment.test.rb
- checkers/ruby/rails_unsafe_direct_assignment.yml
This PR adds a new Ruby checker to detect the use of `attr_accessible :all`, which enables mass assignment of all model attributes. This practice can lead to serious security vulnerabilities, including privilege escalation and unauthorized data modifications. Attackers can exploit this to alter sensitive fields such as `admin`, `role`, or `balance` through crafted requests.
- Usage of `attr_accessible :all` in Rails models.
- **Privilege Escalation:** Attackers can gain elevated permissions by modifying sensitive fields.  
- **Unauthorized Data Access:** Mass assignment can lead to unintended attribute changes.  
- **Data Integrity Risks:** Allows untrusted input to manipulate protected model attributes.
Instead of using `attr_accessible :all`, use …
> checker: ruby_rails_unsafe_direct_assignment

- checkers/ruby/rails_samesite_cookie.test.rb
- checkers/ruby/rails_samesite_cookie.yml
This PR adds a new Ruby checker to detect insecure cookie configurations using `SameSite=None` or missing the `same_site` attribute in Rails applications. Using `SameSite=None` allows cookies to be sent with cross-site requests, increasing the risk of Cross-Site Request Forgery (CSRF) attacks. Without proper configuration, attackers can exploit this to impersonate users or perform unauthorized actions.
The checker flags the following cases:  
- Usage of `same_site: :none` in session or cookie store configurations.  
- Missing `same_site` attribute in session or cookie store configurations.
- **CSRF Vulnerability:** Cookies sent with cross-origin requests can be used in CSRF attacks.  
- **User Impersonation:** Attackers can exploit this to perform actions on behalf of authenticated users. …
> checker: ruby_rails_samesite_cookie

- checkers/ruby/rails_http_hardcoded_passwd.test.rb
- checkers/ruby/rails_http_hardcoded_passwd.yml
This PR adds a new Ruby checker to identify instances of hardcoded passwords in HTTP authentication using `http_basic_authenticate_with`. Hardcoding passwords in source code exposes sensitive credentials, increasing the risk of leaks and unauthorized access.
The checker flags cases where:  
- `http_basic_authenticate_with` is used with a direct string assignment to the `password` parameter.  
- **Security Risk:** Attackers can extract hardcoded passwords from the codebase.  
- **Version Control Exposure:** Credentials may be exposed in Git history.  
- **Credential Management Issues:** Hardcoded passwords complicate rotation and increase maintenance burden.  
Replace hardcoded passwords with secure credential management solutions:  
- Use environment variables: `ENV['ADMIN_PASSWORD']`. …
> checker: ruby_rails_http_hardcoded_passwd

- checkers/ruby/rails_force_ssl.test.rb
- checkers/ruby/rails_force_ssl.yml
This PR introduces a new Ruby checker that detects when SSL enforcement is disabled using `config.force_ssl = false`. Disabling SSL exposes applications to plaintext HTTP traffic, increasing the risk of data interception and man-in-the-middle (MITM) attacks.
The checker flags instances where:  
- `force_ssl` is explicitly set to `false`.  
- **Security Vulnerability:** Unencrypted HTTP traffic can be intercepted and manipulated.  
- **Compliance Issues:** Most security standards (e.g., PCI-DSS, GDPR) require encrypted data transmission.  
- **User Trust:** Browsers mark HTTP sites as insecure, harming user confidence.  
Enable SSL by setting `config.force_ssl = true` in your production environment to enforce HTTPS.  
```ruby
Rails.application.configure do
config.force_ssl = false
end …
```
> checker: ruby_rails_force_ssl

- checkers/ruby/md5_weak_hash.test.rb
- checkers/ruby/md5_weak_hash.yml
Issue:
MD5 is an outdated and insecure hashing algorithm that is vulnerable to collision and preimage attacks. 
It is unsuitable for hashing passwords or securing sensitive data.
Why is this a problem?
- Collisions: Attackers can generate two different inputs that produce the same hash.
- Fast Computation: MD5 is extremely fast, making brute-force attacks feasible.
- Cryptographic Breaks: MD5 has been broken since 2004 and is not considered secure.
Remediation:
- Do not use MD5 for security-sensitive operations.
- Use SHA-256 or SHA-512 for general-purpose hashing.
- Use BCrypt, Argon2, or PBKDF2 for password hashing.
Example Fix:
```ruby
require 'digest'
require 'bcrypt'
password = "SecurePassword123"
hashed_password_md5 = Digest::MD5.hexdigest(password)
hashed_password_sha256 = …
```
> checker: ruby_md5_weak_hash

- checkers/ruby/dsa_weak_crypto.test.rb
- checkers/ruby/dsa_weak_crypto.yml
This PR adds a Ruby checker that detects the use of DSA (`OpenSSL::PKey::DSA`) for cryptographic operations. DSA is outdated, insecure, and should not be used for modern cryptographic needs.
The checker flags instances where:  
- `OpenSSL::PKey::DSA` is used to generate or handle keys.
- **Weak Key Sizes:** DSA commonly uses 1024-bit keys, which are vulnerable to brute-force attacks.  
- **Private Key Exposure:** Poor randomness in DSA signatures can leak private keys.  
- **Non-Compliance:** Modern standards like NIST discourage the use of DSA.  
**Use Modern Cryptography:**  
- **Password Hashing:** Use `BCrypt` for securely hashing passwords.  
- **Encryption:** Use `AES-256-GCM` for secure encryption needs.  
```ruby
require 'bcrypt'
require 'openssl'
dsa = …
```
> checker: ruby_dsa_weak_crypto

- checkers/go/math_rand.test.go
- checkers/go/math_rand.yml
This PR adds a Go checker that detects the use of the `math/rand` package for cryptographic operations, which is insecure.
The checker flags instances where the `"math/rand"` package is imported.
- **Deterministic Output:** `math/rand` produces predictable random numbers.  
- **Security Risk:** Predictable randomness can lead to token and key guessing.  
- **Not Meant for Crypto:** The Go documentation advises against using `math/rand` for security purposes.
**Use `crypto/rand` for cryptographic operations:**  
- Securely generate random numbers using `crypto/rand.Int`.  
- Use `rand.Reader` for cryptographically secure randomness.  
```go
import (
"crypto/rand"
"fmt"
"math/big"
)
func main() {
n := int64(100)
randomNumber, err := rand.Int(rand.Reader, big.NewInt(n)) …
```
> checker: go_math_rand

- checkers/go/pprof_endpoint_automatic_exposure.test.go
- checkers/go/pprof_endpoint_automatic_exposure.yml
This PR introduces a Go checker that detects imports of the `net/http/pprof` package, which automatically exposes the `/debug/pprof` endpoint.
The checker flags instances where the `"net/http/pprof"` package is imported, even with a blank identifier.
- **Information Disclosure:** Exposes runtime details (goroutines, heap, CPU profiles) that attackers can exploit.  
- **Production Risk:** Accessible endpoints can leak sensitive operational data.  
- **Security Concern:** Profiling information should not be publicly exposed in production environments.
Use build tags to include `pprof` only in non-production builds:  
```go
//go:build debug
import _ "net/http/pprof"
```
`test/**,*_test.rb,tests/**,__tests__/**`
[pprof security considerations](https://github.com/golang/go/issues/22085)
> checker: go_pprof_endpoint_automatic_exposure

- checkers/go/postgres_conn_raw_passwd.test.go
- checkers/go/postgres_conn_raw_passwd.yml
This PR adds a Go checker that detects hardcoded PostgreSQL connection strings containing plaintext passwords.
The checker flags the following pattern:  
- Calls to `sql.Open` where the connection string includes a hardcoded PostgreSQL URL with embedded credentials (e.g., `"postgres://user:password@host"`).
- **Credential Exposure:** Hardcoded passwords can be easily extracted from source code, compromising databases.  
- **Version Control Risks:** Sensitive information might be exposed if the code is shared or pushed to repositories.  
- **Operational Security:** Hardcoded secrets hinder proper credential rotation and secure management practices.
Avoid hardcoding credentials. Use environment variables instead:  
```go
import (
"database/sql"
"fmt"
"log"
"os"
_ "github.com/lib/pq"
)
func …
```
> checker: go_postgres_conn_raw_passwd

- checkers/go/postgres_config_raw_passwd.test.go
- checkers/go/postgres_config_raw_passwd.yml
This PR introduces a Go checker that detects hardcoded PostgreSQL passwords within `pg.Options` structs.
The checker flags:  
- Composite literals of type `pg.Options` containing a `Password` field assigned with a hardcoded string.  
- **Credential Exposure:** Hardcoded passwords make databases vulnerable to unauthorized access.  
- **Version Control Risks:** Secrets in code can be accidentally pushed to repositories.  
- **Operational Risks:** Hardcoded credentials hinder secure credential rotation practices.  
Replace hardcoded passwords with environment variable lookups:  
```go
import (
"os"
"github.com/go-pg/pg/v10"
)
func main() {
options := &pg.Options{
User:     "pguser",
Password: os.Getenv("PG_PASSWORD"), // Secure alternative
Addr:     "localhost:5432",
Database: "exampledb",
} …
```
> checker: go_postgres_config_raw_passwd

- checkers/go/os_create_file_default_permission.test.go
- checkers/go/os_create_file_default_permission.yml
This PR introduces a Go checker that detects the usage of `os.Create` for file creation without specifying explicit permissions. By default, `os.Create` sets file permissions to `0666`, which may expose the file to unauthorized access.
The checker flags:  
- Calls to `os.Create()` that do not define explicit file permissions.  
- **Unintended Access:** Default permissions (`0666`) may allow other system users to read or write sensitive files.  
- **Data Integrity Risk:** Files created with overly permissive settings can be altered by unauthorized users.  
- **Compliance Issues:** Certain standards require explicit permission management for sensitive files.  
Instead of using `os.Create`, use `os.OpenFile` and define proper permissions (e.g., `0600` for read/write by the owner only): …
> checker: go_os_create_file_default_permission

- checkers/go/net_bind_all_interfaces.test.go
- checkers/go/net_bind_all_interfaces.yml
This PR adds a Go checker that detects when applications bind to all network interfaces (`0.0.0.0` or `:port`) using `net.Listen`. Binding to all interfaces can unintentionally expose services to external networks, increasing the risk of unauthorized access.
The checker flags:  
- Calls to `net.Listen` with addresses like `"0.0.0.0:port"` or `":port"`.
- **Unrestricted Access:** Exposing services on all interfaces can allow external attackers to reach internal services.  
- **Attack Surface Expansion:** Services unintentionally exposed can be targeted by port scanning tools.  
- **Compliance Concerns:** Certain regulations require limiting network exposure of sensitive services.  
If external access is not required, bind to `localhost`:  
```go
package main
import (
"log"
"net"
)
func …
```
> checker: go_net_bind_all_interfaces

- checkers/java/unsafe_path_traversal.test.java
- checkers/java/unsafe_path_traversal.yml
This PR introduces a new java security checker named `unsafe_file_traversal` to detect potential path traversal vulnerabilities in Java. Improper handling of file paths, especially when constructed dynamically with user input, can allow attackers to access unauthorized files, leading to security risks such as information disclosure, arbitrary file access, or file manipulation.
The checker flags the following unsafe patterns:
This checker excludes test directories and vendor dependencies to reduce false positives.
> java: unsafe file traversal

- checkers/go/mysql_conn_raw_passwd.test.go
- checkers/go/mysql_conn_raw_passwd.yml
This PR introduces a Go checker that detects hardcoded MySQL credentials in connection strings passed to `sql.Open`. Hardcoding sensitive information like database usernames and passwords can expose your application to unauthorized access if the source code is leaked or shared.
The checker flags:  
- Calls to `sql.Open` with a connection string containing inline credentials (e.g., `"user:password@tcp(...)"`).  
- **Credential Exposure:** If code is stored in version control (e.g., GitHub), attackers can easily extract credentials.  
- **Increased Attack Surface:** Exposed credentials can lead to unauthorized data access or data loss.  
- **Compliance Risks:** Storing sensitive data in source code may violate security best practices and compliance requirements.  
1. **Use Environment …
> checker: go_mysql_conn_raw_passwd

- checkers/go/missing_error_file_open.test.go
- checkers/go/missing_error_file_open.yml
This PR introduces a checker that detects when the error returned by `os.Open` is ignored. Failing to handle this error can lead to runtime panics, silent failures, and potential security vulnerabilities.
The checker flags cases where:  
- `os.Open` or related methods are called.  
- The returned error is assigned to `_` (ignored).  
- **Nil Pointer Dereference:** Using the file handle without verifying the error can cause a panic if the file didn't open.  
- **Silent Failures:** Ignoring the error may lead to incorrect assumptions, such as processing nonexistent files.  
- **Security Concerns:** Files containing critical configurations or credentials may be bypassed if errors are ignored.  
---
```go
f, _ := os.Open("config.txt") // Error ignored
data, _ := ioutil.ReadAll(f) …
```
> checker: go_missing_error_file

- checkers/go/fmt_print_in_prod.test.go
- checkers/go/fmt_print_in_prod.yml
This PR introduces a new checker to discourage the use of `fmt.Print*` functions in production Go code.
- `fmt.Print`, `fmt.Println`, or `fmt.Printf` are used in production code.
The `fmt.Print*` functions are convenient for debugging and development but should be avoided in production environments because:
- They can expose sensitive information to unauthorized users.
- Frequent console output can degrade application performance.
- They lack logging levels and structured logging, making maintenance and debugging more difficult.
Instead of `fmt.Print*`, use a structured logging library such as `log`, `logrus`, or `zap`.
```go
fmt.Println("Hello, World!") // Avoid using fmt in production
```
```go
log.Println("Hello, World!") // Use structured logging …
```
> checker: go_fmt_print_in_prod

- checkers/go/md5_weak_hash.test.go
- checkers/go/md5_weak_hash.yml
This PR adds a checker that detects imports of the `crypto/md5` package, highlighting the use of the weak MD5 hashing algorithm. MD5 is susceptible to collision attacks, making it unsuitable for hashing sensitive data.
---
- **Collision Vulnerability:** Attackers can generate different inputs with the same hash, compromising data integrity.  
- **Preimage Attacks:** It's feasible to reverse-engineer the hash back to its original input.  
- **Compliance Issues:** Many security standards (e.g., PCI-DSS, NIST) prohibit the use of MD5 in security-sensitive contexts.  
---
```go
import (
"crypto/md5"
"fmt"
)
func main() {
data := []byte("sensitive_data")
hash := md5.Sum(data) // Vulnerable to collisions
fmt.Printf("MD5 Hash: %x\n", hash)
}
```
`test/**,*_test.go,tests/**,__tests__/**`
[NIST …
> checker: go_md5_weak_hash

- checkers/go/jwt_none_algorithm.test.go
- checkers/go/jwt_none_algorithm.yml
This PR introduces a security check that detects and prevents the usage of the `'none'` algorithm in JWT. The `'none'` algorithm disables signature verification, exposing applications to severe security vulnerabilities like token forgery and unauthorized access.
- **Bypass Protection:** Attackers can send tokens with `'none'` as the algorithm, tricking applications into accepting unsigned tokens.  
- **Security Breach Risk:** Vulnerabilities like this have been actively exploited in the past. ([Auth0 Blog on JWT Vulnerabilities](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/))  
- **Compliance:** Prevents usage of insecure JWT configurations, meeting security best practices and audit requirements.  
```go
import "github.com/golang-jwt/jwt"
func unsafeJWT() { …
```
> checker: go_jwt_none_algorithm

- checkers/go/jwt_harcoded_signing_key.test.go
- checkers/go/jwt_harcoded_signing_key.yml
This PR introduces a security check that flags the use of hardcoded JWT signing keys, which can be easily exposed and exploited. Developers are encouraged to load signing keys securely through environment variables or secret management solutions.
- **Exposure Risk:** Hardcoded keys are prone to leaks through code sharing or version control.  
- **Token Forgery:** Attackers with access to the key can craft valid JWTs to bypass security.  
- **Privilege Escalation:** Unauthorized users can gain elevated privileges using forged tokens.  
```go
import "github.com/golang-jwt/jwt"
func insecureJWT() {
token := jwt.New(jwt.SigningMethodHS256)
tokenString, err := token.SignedString([]byte("my_secret_key")) // Hardcoded key
panic(err)
}
fmt.Println("Token:", tokenString)
}
```
``` …
```
> checker: go_jwt_hardcoded_signing_key

- checkers/go/insecure_cookie.test.go
- checkers/go/insecure_cookie.yml
This PR adds a security check to detect usage of `http.SetCookie` without the `Secure` flag, ensuring cookies are transmitted only over HTTPS to prevent interception.
- **Data Leakage:** Without the `Secure` flag, cookies can be transmitted over unencrypted connections, exposing sensitive information.  
- **Session Hijacking:** Attackers can intercept cookies over HTTP and hijack user sessions.  
- **Compliance:** Secure cookie handling is a requirement for many security standards and best practices.  
```go
http.SetCookie(w, &http.Cookie{
Name:  "session_id",
Value: "xyz123", // No Secure flag
})
```
```
http.SetCookie(w, &http.Cookie{
Name:   "session_id",
Value:  "xyz123",
Secure: true, // Secure flag ensures cookie is sent only over HTTPS
})
``` …
> checker: go_insecure_cookie

- checkers/go/http_file_server.test.go
- checkers/go/http_file_server.yml
This PR adds a new Go checker to detect the unsafe use of `http.FileServer`, which can expose directory listings and allow attackers to browse and access sensitive files. By default, `http.FileServer(http.Dir("."))` serves the entire directory, including hidden and sensitive files, increasing the risk of unauthorized data exposure.
This checker flags instances where `http.FileServer` is used with `http.Dir`, which can lead to unintended directory listings:
- Calls to `http.FileServer` where `http.Dir` is used as an argument.
To mitigate security risks, consider restricting file access and disabling directory listing:
```go
http.Handle("/files/", http.StripPrefix("/files/", http.FileServer(http.Dir(".")))) // Vulnerable: exposes entire working directory
```
```go
mux := http.NewServeMux() …
```
> checker: go_http_file_server

- checkers/go/html_req_template_injection.test.go
- checkers/go/html_req_template_injection.yml
This PR adds a new Go checker to detect security risks associated with rendering user-controlled data using `html/template` without proper sanitization. Improper handling of user inputs in templates can lead to **Server-Side Template Injection (SSTI)**, allowing attackers to execute arbitrary code, leak sensitive data, or launch Cross-Site Scripting (XSS) attacks.
- User-controlled input (from `r.Cookie`, `r.URL.Query().Get`, or `r.FormValue`) is directly mapped to a template.
- The template executes user input without proper sanitization.
To mitigate security risks, always sanitize user inputs and ensure context-aware encoding before rendering:
```go
http.HandleFunc("/unsafe", func(w http.ResponseWriter, r *http.Request) {
r.ParseForm()
data := …
```
> checker: go_html_req_template_injection

- checkers/go/grpc_server_insecure_tls.test.go
- checkers/go/grpc_server_insecure_tls.yml
This PR adds a new Go checker to detect insecure gRPC server configurations where `grpc.NewServer` is used without TLS credentials. Running a gRPC server without TLS exposes communications to **man-in-the-middle (MITM) attacks**, allowing attackers to intercept or manipulate sensitive data.
- `grpc.NewServer` is called without `grpc.Creds`, indicating the absence of TLS encryption.
To secure gRPC servers, always provide TLS credentials using `grpc.Creds`:
```go
server := grpc.NewServer() // Insecure: No TLS credentials
```
```go
creds, err := credentials.NewServerTLSFromFile("server.crt", "server.key")
log.Fatalf("Failed to load TLS keys: %v", err)
}
server := grpc.NewServer(grpc.Creds(creds)) // Secure: TLS enabled
```
To reduce noise, …
> checker: go_grpc_server_insecure_tls

- checkers/go/grpc_client_insecure_tls.test.go
- checkers/go/grpc_client_insecure_tls.yml
This PR adds a new Go checker to detect insecure usage of `grpc.WithInsecure()` in gRPC client connections. Using `grpc.WithInsecure()` disables Transport Layer Security (TLS), exposing applications to **Man-in-the-Middle (MITM) attacks**, data interception, and unauthorized access.
- The `grpc.Dial()` function is called with `grpc.WithInsecure()`.
- This disables TLS encryption and allows unencrypted communication between client and server.
To secure gRPC client connections, use **TLS with proper certificate validation**:
```go
import (
"google.golang.org/grpc"
)
conn, err := grpc.Dial("example.com:50051", grpc.WithInsecure()) // Insecure: disables transport security
log.Fatalf("Connection failed: %v", err)
}
defer conn.Close()
``` …
> checker: go_grpc_client_insecure_tls

- checkers/go/des_weak_crypto.test.go
- checkers/go/des_weak_crypto.yml
This PR introduces a security checker to detect the use of weak cryptographic algorithms, specifically DES and 3DES, which are considered cryptographically insecure.
- `des.NewCipher` or `des.NewTripleDESCipher` are used, as DES and 3DES are deprecated and vulnerable to brute-force attacks.
Instead of DES, use AES encryption to ensure secure cryptographic operations:
```go
import "crypto/des"
key := []byte("weak-key-123")
cipher, err := des.NewCipher(key) // Weak encryption
panic(err)
}
```
```go
import "crypto/aes"
key := []byte("stronger-key-128-bit")
cipher, err := aes.NewCipher(key) // Secure encryption
panic(err)
}
```
To reduce noise, this checker does not flag occurrences in:
- Test files (`test/**`, `*_test.go`, …
> checker: go_des_weak_crypto

- checkers/go/cgi_import.test.go
- checkers/go/cgi_import.yml
This PR adds a new Go checker to detect the usage of the deprecated and insecure `net/http/cgi` package.
- The `net/http/cgi` package is imported in Go source files.
The `net/http/cgi` package is deprecated and insecure, posing risks such as:
- **Command Injection**: CGI-based applications are more susceptible to command injection attacks.
- **Performance Issues**: CGI introduces additional process creation overhead, making it inefficient compared to modern web frameworks.
- **Outdated Architecture**: Modern web development favors more secure and scalable alternatives, such as HTTP handlers and middleware.
Instead of `net/http/cgi`, use the `net/http` package to build modern, secure HTTP servers.
```go
import "net/http/cgi"
```
```go
import "net/http" …
```
> checker: go_cgi_import

- checkers/go/unsafe_pkg.test.go
- checkers/go/unsafe_pkg.yml
This PR introduces a new Go checker to detect the usage of the `unsafe` package, which allows low-level memory manipulation and can lead to security vulnerabilities.
- The `unsafe` package is imported, which can bypass Go’s type safety and lead to unpredictable behavior.
Using the `unsafe` package can:
- Bypass Go’s memory safety guarantees, leading to memory corruption.
- Introduce hard-to-debug security vulnerabilities.
- Make code less portable and maintainable across different Go versions.
Use standard Go libraries and idiomatic constructs to handle memory safely.
```go
import "unsafe"
func unsafePointerConversion() {
var x int = 42
ptr := unsafe.Pointer(&x) // Unsafe memory manipulation
_ = ptr
}
```
```go
func safeMemoryUsage() {
var x int = 42
y …
```
> checker: go_unsafe_pkg

- checkers/go/tls_insecure.test.go
- checkers/go/tls_insecure.yml
This PR adds a new Go checker to detect insecure TLS configurations where `tls.Config.InsecureSkipVerify` is set to `true`.
- `tls.Config{ InsecureSkipVerify: true }` is used, which disables TLS certificate verification.
Disabling TLS certificate verification exposes applications to **man-in-the-middle (MITM) attacks**, allowing attackers to intercept and modify sensitive data. This can compromise the confidentiality and integrity of communications.
Instead of disabling certificate verification, use a properly configured **RootCAs** to ensure secure TLS connections.
```go
tlsConfig := &tls.Config{
InsecureSkipVerify: true, // Insecure: Skips TLS verification
}
```
```go
import "crypto/x509"
rootCAs, err := x509.SystemCertPool() …
```
> checker: go_tls_insecure

- checkers/go/tls_config_minver.test.go
- checkers/go/tls_config_minver.yml
This PR adds a new Go checker to detect missing `MinVersion` settings in `tls.Config`, which can lead to insecure TLS connections.
- A `tls.Config` struct is initialized without explicitly setting the `MinVersion` field.
To enforce secure TLS versions, set `MinVersion` to `tls.VersionTLS12` or higher:
```go
config := &tls.Config{}
```
```go
config := &tls.Config{
MinVersion: tls.VersionTLS12,
}
```
To reduce noise, this checker does not flag occurrences in:
- Test files (`test/**`, `*_test.go`, `tests/**`, `__tests__/**`)
- [[OWASP Transport Layer Protection Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html)]
> checker: go_tls_config_minver

- checkers/go/reflect_pkg.test.go
- checkers/go/reflect_pkg.yml
This PR adds a new Go checker to detect the use of the `reflect` package, which should be avoided unless absolutely necessary due to performance and maintainability concerns.
- The `reflect` package is imported in a Go file.
Reflection should only be used when no better alternatives (such as generics or type assertions) exist.
```go
import (
"reflect"
)
func getTypeName(val interface{}) string {
return reflect.TypeOf(val).Name() // Reflection introduces runtime overhead
}
```
```go
func printType(val interface{}) {
if str, ok := val.(string); ok {
fmt.Println("Type is string:", str)
}
}
```
```go
func printType(val interface{}) {
switch v := val.(type) {
case int:
fmt.Println("int:", v)
case string:
fmt.Println("string:", v)
default: …
```
> checker: go_reflect_pkg

- checkers/go/samesite_cookie.test.go
- checkers/go/samesite_cookie.yml
This PR adds a new Go checker to detect insecure usage of the `SameSite=None` attribute in cookies, which can increase the risk of Cross-Site Request Forgery (CSRF) attacks.
- `http.SetCookie()` is called without setting `SameSite=Lax` or `SameSite=Strict`, potentially allowing CSRF attacks.
- The `SameSite=None` attribute is used without additional security mitigations.
To mitigate CSRF risks, configure cookies with appropriate `SameSite` attributes:
```go
http.SetCookie(w, &http.Cookie{
Name:  "session_id",
Value: "secure_value",
SameSite: http.SameSiteNoneMode, //  Insecure: Allows cross-origin requests
})
```
```go
http.SetCookie(w, &http.Cookie{
Name:     "session_id",
Value:    "secure_value",
SameSite: http.SameSiteLaxMode, //  Secure: Mitigates …
```
> checker: go_samesite_cookie

- checkers/checker.go
- checkers/python/insecure-urllib-ftp.go
- checkers/python/testdata/insecure-urllib-ftp.test.py
- checkers/python/use-ftp-tls.test.py
- checkers/python/use-ftp-tls.yml
This PR adds checkers to detect insecure FTP connections. Using FTP links in `urllib` can cause security vulnerabilities as they are not encrypted. Using SFTP is a safer alternative. Since, `urllib` does not support SFTP, a different library must be used.
```
echo "Testing built-in rules..."
./bin/globstar test -d checkers
Running test case: avoid_add.yml
Running test case: avoid_latest.yml
Running test case: avoid_sudo.yml
Running test case: cgi_import.yml
Running test case: des_weak_crypto.yml
Running test case: fmt_print_in_prod.yml
Running test case: grpc_client_insecure_tls.yml
Running test case: grpc_server_insecure_tls.yml
Running test case: html_req_template_injection.yml
Running test case: http_file_server.yml
Running test case: insecure_cookie.yml …
```
> checker(python): add checkers to detect insecure ftp connections in `urllib`

- checkers/python/globals-as-template-context.test.py
- checkers/python/globals-as-template-context.yml
Test logs:
```
Running test case: globals-as-template-context.yml
All tests passed%                    
```
> chore: add checker to detect globals context in django render method

- checkers/python/jwt-python-none-alg.test.py
- checkers/python/jwt-python-none-alg.yml
Test logs
```
Running test case: jwt-python-none-alg.yml
All tests passed%                  
```
> chore: add checker to detect 'none' algo in JWT token encode/decode method

- checkers/python/app-run-with-bad-host.test.py
- checkers/python/app-run-with-bad-host.yml
Test logs:
```
echo "Testing built-in rules..."
Running test case: avoid_add.yml
Running test case: avoid_latest.yml
Running test case: avoid_sudo.yml
Running test case: app-run-with-bad-host.yml
All tests passed        globstar.dev/cmd/globstar               coverage: 0.0% of statements
globstar.dev/pkg/config         coverage: 0.0% of statements
globstar.dev/pkg/cli            coverage: 0.0% of statements
ok      globstar.dev/pkg/analysis       0.005s  coverage: 22.7% of statements
Total …
```
> chore: add checker to detect flask app running on insecure host

- checkers/python/avoid_assert.test.py
- checkers/python/avoid_assert.yml
Using assert statements for enforcing constraints is risky because they are removed when Python optimizes for production code (`python -O`).  This can lead to unintended behaviour, especially for security checks and critical logic. Instead, use explicit condition checks with exceptions (e.g., `if not condition: raise ValueError(...)`).
Refer to [Python docs for assert](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement) about the behaviour in optimised code.
> [Feat] Python: checker for usage of assert statements

- checkers/checker.go
- checkers/python/django-insecure-pickle-deserialize.go
- checkers/python/testdata/django-insecure-pickle-deserialize.test.py
This PR adds a checker to detect insecure deserialization with  `pickle`- backed or `yaml` library with user tainted data. This may cause potential Remote Code Execution vulnerabilities.
> checker: detect insecure pickle deserialization with user tainted data

- checkers/checker.go
- checkers/python/django-request-data-write.go
- checkers/python/django-request-httpresponse.go
- checkers/python/testdata/django-request-data-write.test.py
- checkers/python/testdata/django-request-httpresponse.test.py
This PR adds checker for the following:
- `file.write()` method call tainted with dynamic data from a `request` call
- `HttpResponse` and `HttpResponseBadRequest` tainted with dynamic data from `request` call
> checker: request tainted file write and request tainted `HttpResponse`/`HttpResponseBadRequest`

- checkers/checker.go
- checkers/python/django-request-data-write.go
- checkers/python/django-sql-injection.go
- checkers/python/django-ssrf-injection.go
- checkers/python/testdata/django-sql-injection.test.py
- checkers/python/testdata/django-ssrf-injection.test.py
This PR adds a checkers to detect
- SSRF attacks due to user data received from `request` calls being passed into server side `get` requests.
- SQL injection attacks due to user data from `request` calls being passed into `RawSQL`, `cursor.execute` and `object.raw()` methods
> checker: detect user data from python `request` passed into method calls causing injection vulnerabilities

- checkers/checker.go
- checkers/python/dangerous-create-exec.go
- checkers/python/testdata/dangerous-create-exec.test.py
Test logs
```
./bin/globstar test -d checkers
Running test case: avoid_add.yml
Running test case: avoid_latest.yml
Running test case: avoid_sudo.yml
Running test case: hashid-with-django-secret.yml
Running test case: weak-ssl-version.yml
Running tests in checkers/javascript/testdata for analyzers:
Running tests for analyzer no-double-eq
Running tests in checkers/python/testdata for analyzers:
Running tests for analyzer dangerous-create-exec
All tests passed        globstar.dev/cmd/globstar               coverage: 0.0% of …
```
> checker(python): dangerous subprocess exec in aws-lambda handler functions

- analysis/analyzer.go
- analysis/analyzer_test.go
- pkg/analysis/analyze.go
- pkg/analysis/analyze_test.go
- pkg/analysis/language.go
- pkg/analysis/pattern_rule.go
This PR introduces support for `skipcq` comments to ignore specific issues in the source code.
Fixes #135
> feat: add support for `skipcq` comments to ignore issues

- analysis/analyzer.go
- analysis/analyzer_test.go
- pkg/analysis/analyze.go
- pkg/analysis/analyze_test.go
`skipcq` comments can now take more than target checker name to suppress
> enh: support multiple checker ids in skipcq directive
